# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowMain(object):
    def setupUi(self, windowMain):
        windowMain.setObjectName("windowMain")
        windowMain.resize(563, 420)
        self.label = QtWidgets.QLabel(windowMain)
        self.label.setGeometry(QtCore.QRect(70, 150, 351, 121))
        self.label.setObjectName("label")

        self.retranslateUi(windowMain)
        QtCore.QMetaObject.connectSlotsByName(windowMain)

    def retranslateUi(self, windowMain):
        _translate = QtCore.QCoreApplication.translate
        windowMain.setWindowTitle(_translate("windowMain", "Form"))
        self.label.setText(_translate("windowMain", "ыыыыыыыыыыыыыыыыыы"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    windowMain = QtWidgets.QWidget()
    ui = Ui_windowMain()
    ui.setupUi(windowMain)
    windowMain.show()
    sys.exit(app.exec_())
